const monthsEl = document.getElementById('months');
const yearEl = document.getElementById('anio');
const titleEl = document.getElementById('titulo');
const vacCount = document.getElementById('vacCount');
const fesCount = document.getElementById('fesCount');
let mode = 'vacaciones';
let viewMode = 'accordion';
let data = { titulo: 'Vacaciones 2026', anio: 2026, vacaciones: [], festivos: [] };
const festivosBase = [[1,1],[1,5],[3,19],[3,28],[5,17],[6,24],[7,25],[8,15],[8,16],[10,12],[11,1],[12,6],[12,8],[12,25]];
function key(y,m,d){return `${y.toString().padStart(4,'0')}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
function easter(year){const a=year%19,b=Math.floor(year/100),c=year%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),month=Math.floor((h+l-7*m+114)/31),day=((h+l-7*m+114)%31)+1;return new Date(year,month-1,day)}
function holyWeek(year){const pascua=easter(year);const j=new Date(pascua);j.setDate(pascua.getDate()-3);const v=new Date(pascua);v.setDate(pascua.getDate()-2);return [key(j.getFullYear(),j.getMonth()+1,j.getDate()),key(v.getFullYear(),v.getMonth()+1,v.getDate())]}
function applyFestivosBase(){const y=data.anio;const set=new Set(data.festivos);festivosBase.forEach(([m,d])=>set.add(key(y,m,d)));holyWeek(y).forEach(d=>set.add(d));data.festivos=[...set].sort()}
function render(){titleEl.value=data.titulo;yearEl.value=data.anio;monthsEl.innerHTML='';monthsEl.className='months' + (viewMode==='year' ? ' year-view' : '');const vacSet=new Set(data.vacaciones),fesSet=new Set(data.festivos);for(let month=1;month<=12;month++){const details=document.createElement('details');details.className='month';if(viewMode==='year' || month===1)details.open=true;const summary=document.createElement('summary');summary.innerHTML=`<span>${new Date(data.anio,month-1,1).toLocaleDateString('es-ES',{month:'long'})}</span><span>▾</span>`;details.appendChild(summary);const body=document.createElement('div');body.className='month-body';const legend=document.createElement('div');legend.className='legend';legend.textContent='Toca un día para marcarlo según el modo activo';body.appendChild(legend);const weekdays=document.createElement('div');weekdays.className='weekdays';['Lu','Ma','Mi','Ju','Vi','Sa','Do'].forEach(d=>{const el=document.createElement('div');el.textContent=d;weekdays.appendChild(el)});body.appendChild(weekdays);const first=new Date(data.anio,month-1,1);let start=(first.getDay()+6)%7;const daysInMonth=new Date(data.anio,month,0).getDate();let day=1;for(let w=0;w<6;w++){const row=document.createElement('div');row.className='week';for(let i=0;i<7;i++){const cell=document.createElement('div');if((w===0&&i<start)||day>daysInMonth){cell.className='day empty'}else{const k=key(data.anio,month,day);cell.className='day';if(vacSet.has(k))cell.classList.add('vacaciones');if(fesSet.has(k))cell.classList.add('festivo');cell.textContent=day;cell.onclick=()=>toggleDay(k);day++}row.appendChild(cell)}body.appendChild(row);if(day>daysInMonth)break}details.appendChild(body);monthsEl.appendChild(details)}updateStats()}
function toggleDay(k){const vac=new Set(data.vacaciones),fes=new Set(data.festivos);if(mode==='vacaciones'){if(vac.has(k))vac.delete(k);else{vac.add(k);fes.delete(k)}}else{if(fes.has(k))fes.delete(k);else{fes.add(k);vac.delete(k)}}data.vacaciones=[...vac].sort();data.festivos=[...fes].sort();render()}
function updateStats(){vacCount.textContent=data.vacaciones.length;fesCount.textContent=data.festivos.length}
document.querySelectorAll('.mode').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.mode').forEach(b=>b.classList.remove('active'));btn.classList.add('active');mode=btn.dataset.mode;});
document.getElementById('actualizarAnio').onclick=()=>{data.anio=parseInt(yearEl.value,10)||new Date().getFullYear();data.titulo=titleEl.value.trim()||`Vacaciones ${data.anio}`;data.vacaciones=[];data.festivos=[];applyFestivosBase();render()};
document.getElementById('exportJson').onclick=()=>{data.titulo=titleEl.value.trim()||`Vacaciones ${data.anio}`;const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`vacaciones_${data.anio}.json`;a.click();URL.revokeObjectURL(a.href)};
document.getElementById('importJsonBtn').onclick=()=>document.getElementById('importJson').click();
document.getElementById('importJson').onchange=(e)=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const obj=JSON.parse(r.result);data={titulo:obj.titulo||`Vacaciones ${obj.anio||new Date().getFullYear()}`,anio:obj.anio||new Date().getFullYear(),vacaciones:obj.vacaciones||[],festivos:obj.festivos||[]};render()}catch(err){alert('JSON no válido')}};r.readAsText(file)};
document.getElementById('printBtn').onclick=()=>{data.titulo=titleEl.value.trim()||`Vacaciones ${data.anio}`;document.title=data.titulo;render();setTimeout(()=>window.print(),150)};
applyFestivosBase();render();

document.querySelectorAll('.viewmode').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.viewmode').forEach(b=>b.classList.remove('active'));btn.classList.add('active');viewMode=btn.dataset.view;render();});
